### ISSUE TITLE
Provide support for Binary Data

### ISSUE THREAD

**Issue by jonnyreeves** [jonnyreeves/chunked-request#12]
It would great to use this as a transport for [Protobuf.js](https://github.com/dcodeIO/ProtoBuf.js/); this could then be combined with [mwitkow/grpc-browser-compat](https://github.com/mwitkow/grpc-browser-compat) to provide a [grpc-client](https://github.com/grpc/grpc.github.io/blob/master/docs/tutorials/basic/node.md) for browsers...

**Comment by ariutta** [comment]
This would be pretty cool. But right now, one of the nice things about `chunked-request` is how small it is, as you can see in [this comparison table](https://github.com/visionmedia/superagent/issues/1033#issuecomment-234828880). Adding protobuf.js as a core dependency would eliminate that advantage.

Would it be possible to extract out the minimal HTTP client functionality as one lib and then build on that in another lib?

**Comment by jonnyreeves** [comment]
Ah sorry, I didn't have intentions on adding `protobuf.js` as a dependency; just making it so the chunk parsers work with `ArrayBuffer`s instead of strings.

**Comment by ariutta** [comment]
I see. Would `protobuf.js` be a parser that a user could specify?

**Comment by jonnyreeves** [comment]
> Would protobuf.js be a parser that a user could specify?

Yep exactly.

**Comment by jonnyreeves** [comment]
Landed on v0.5
