### ISSUE TITLE
Match Fetch and WHATWG Streams Spec

### ISSUE THREAD

**Issue by ariutta** [jonnyreeves/chunked-request#16]
We've [discussed](https://github.com/jonnyreeves/chunked-request/issues/13#issuecomment-239617568) matching the [WHATWG streams spec](https://streams.spec.whatwg.org/): async `read` method returns a Promise, which is fulfilled by an ArrayBuffer. I'm understanding that to mean we want to build an abstraction over the various `fetch` and `xhr` implementations so that they all give a `reader` with an async `read` method to the parsers. Here's what it would look like for various implementations:
- Chrome: use native `reader` from `fetch`
- FF: set `responseType` to `moz-chunked-arraybuffer`, get ArrayBuffer(s) from `xhr.response` `progress` event(s), accumulate if needed, resolve `reader.read` Promise
- IE10+: set `responseType` to `ms-stream`, call `readAsArrayBuffer` on `xhr.response` to get an `eventemitter`, get ArrayBuffer(s) from `eventemitter` `progress` event(s), accumulate if needed, resolve `reader.read` Promise
- IE9: set `responseType` to `text`, slice `xhr.responseText` on `progress` event(s) to get chunk(s), convert to ArrayBuffer(s) using [`text-encoding-utf-8`](https://github.com/ariutta/chunked-request/blob/4f6b839633243edc626d9e8dc56008b9e43940e5/src/defaultTransportFactory.js#L7), accumulate if needed, resolve `reader.read` Promise
- Safari: until it supports `fetch`, basically do the same thing as for IE9, except use native `Uint8Array` when converting to ArrayBuffer like [this](https://github.com/ariutta/chunked-request/blob/4f6b839633243edc626d9e8dc56008b9e43940e5/src/defaultTransportFactory.js#L15).

Are we on the same page with this?

**Comment by ariutta** [comment]
Here's a demo of this (`ms-stream` not yet implemented): https://github.com/jonnyreeves/chunked-request/pull/15#issuecomment-241322503

**Comment by ariutta** [comment]
We [want](https://github.com/jonnyreeves/chunked-request/pull/15#issuecomment-241338965) to dedup code for XHR, but I'm not sure how to best do this, because the patch for `ms-stream` needs to handle the `readAsArrayBuffer` method, which returns an `eventemitter`, meaning we have two eventemitters: the XHR response and the result from `readAsArrayBuffer`. So we might not be able to just create a single abstraction by applying browser-specific "patches" to a generic XHR request.

Also, do we want to use `try/catch` (something roughly like [this](https://github.com/ariutta/chunked-request/blob/e8e354d1f018f53f154b3b0ce8ef2593dda39329/src/defaultTransportFactory.js#L126)) for feature detection or use browser detection as we are at present or use a combination of both?

**Comment by jonnyreeves** [comment]
Changing the milestone to 0.6; looking to land 0.5 with binary data support (and fix for chrome) in the mean time as real-life keeps getting in the way :(

**Comment by jonnyreeves** [comment]
Implemented in https://github.com/jonnyreeves/fetch-readablestream
