### ISSUE TITLE
Return ReadableStream

### ISSUE THREAD

**Issue by jimmywarting** [jonnyreeves/chunked-request#21]
How about actually get a ReadableStream back instead of writing a own custom onChunk callback

With ReadableStream you would be able to pipeTo & pipeThrogh others streams
With web-stream-polyfill (npm) this would be a breeze

**Comment by jimmywarting** [comment]
with regards to #19 (cancellation) the way you would do it with ReadableStream is by calling `.error()` that would trigger xhr.abort

**Comment by jimmywarting** [comment]
Played a bit myself with streams and monkey patching xhr: 

This is how i would do it for firefox: https://jsfiddle.net/98L105v3/2/

**Comment by jonnyreeves** [comment]
Thanks @jimmywarting this was an excellent suggestion; I've incorporated your ideas into #20 - I would appreciate your feedback and also any input you and @ariutta have on the future surface API of this library.

**Comment by jimmywarting** [comment]
Now when i look back at my monkey patch I like it since you can choose to overide it or get a new extended xhr (:
