### ISSUE TITLE
Chunked request doesn't work in IE 11 browser

### ISSUE THREAD

**Issue by maheshmb2007** [jonnyreeves/chunked-request#28]
I was surfing internet to find a package to capture http chunked request/response, luckily I found "chunked-request" package, It is very great and met our complete project requirement. But it will work only in Chrome and Firefox, I got some javascript issues in IE browser (Ver 10 and 11). I spent some time and did investigation and came to know that by default "TextEncoder" doesn't support in IE.

Even I have installed "fetch-readablestream" npm package, it has same issue. 

Javascript Error in IE: "'TextEncoder' is undefined"

**Comment by maheshmb2007** [comment]
I Fixed this javascript issue in IE. Below is the code changes.

1. src/impl/xhr.js: 

- Imported “text-encoding” library to provide reference to TextEncoder object, because for IE by default it doesn’t support. So we have to explicitly provide a reference from “text-encoding” module.
import { TextEncoder } from 'text-encoding';

- Provided above module reference to while creating “textEncoder” object to manage http chunked request/response.
const textEncoder = new TextEncoder.TextEncoder();

2. lib/impl/xhr.js: Updated above changes in library version of xhr.js file.

     var _textEncoder = require('text-encoding');
     var textEncoder = new _textEncoder.TextEncoder();

**Comment by jonnyreeves** [comment]
Glad you got this working, although you may wish to consider using a [TextEncoder polyfill](https://github.com/samthor/fast-text-encoding) instead of modifying this library.

**Comment by maheshmb2007** [comment]
As suggested I tried TextEncoder polyfill, but still it didn't worked in IE browser. Getting below javscript error.
"Failed to encode: the 'stream' option is unsupported."
