### ISSUE TITLE
Single file?

### ISSUE THREAD

**Issue by ajselvig** [jonnyreeves/chunked-request#4]
Hey, this project is exactly what I'm looking for, but I'd like to be able to use it in a non-node/npm project. Is there a way to get it as a single js file?

I have npm laying around so I downloaded it and saw that it comes with a lib directory containing the processed javascript, but it's still spread across multiple files (and a directory). I'd really prefer a single file, is this possible?

**Comment by jonnyreeves** [comment]
Yep that's totally possible, just need to invoke browserify with the `--standalone` flag (and [futz around with es6 modules](https://github.com/babel/babelify/issues/139)...)

I'll hook it into a more generic publish script so a `dist` folder is created with each github release from which you can download a single `chunked-request.js` file.

**Comment by jonnyreeves** [comment]
Hey @ajselvig; I've just published [v0.2.1](https://github.com/jonnyreeves/chunked-request/releases/v0.2.1) which includes a `dist/` folder with a standalone ES5 module you can include in a `<script>` tag - let me know if this works for you?

Cheers.

**Comment by ajselvig** [comment]
Yeah, that worked perfectly, thanks!

Just trying to figure out how to get it to use my cookies now...

**Comment by jonnyreeves** [comment]
@ajselvig I'm guessing you're seeing this issue on Chrome?  See #5.

**Comment by ajselvig** [comment]
Yup
